### ISSUE TITLE
[BUG] - MacOS installer fails 

### ISSUE THREAD

**Issue by ac4lt** [FiniteSingularity/obs-composite-blur#103]
**Describe the bug**
I suspect this happens because my home directory is on a removable drive. The installer brings up a prompt asking me if it can have permission to write to a removable drive. Before I can answer, the installer fails.

**To Reproduce**
1. Create a user with a home directory on a removable drive
2. Log in as that user
3. Attempt to install using the Mac installer

**Expected behavior**
successful installation

**Screenshots**
This image shows what happens
<img width="751" alt="Screenshot 2024-06-12 at 2 59 43 PM" src="https://github.com/FiniteSingularity/obs-composite-blur/assets/13646556/69b870c1-0512-4057-9f82-ac377e237189">

**Environment**
 - OS/Version: MacOS 14.5
 - OBS Version: 30.1.2
 - Composite Blur Plugin Version: 1.1.0

**Comment by FiniteSingularity** [comment]
Hi @ac4lt.  Thank you for the issue.

The installer is built using the standard MacOS installer builder.  Any chance you could check your logs/console to see if there are any specific warning getting triggered?  It is a little tricky for me to test, as I dont have a similar setup (my user directory is on my MBPs main drive).

**Comment by FiniteSingularity** [comment]
Unfortunately, I'm unable to replicate this on my Mac, and thus have no way of troubleshooting the issue. If you continue to have this problem, and can provide more details, please feel free to re-open and I'll take a look.
