### ISSUE TITLE
[FEATURE]  background blur

### ISSUE THREAD

**Issue by elkhalafy** [FiniteSingularity/obs-composite-blur#107]
Hi

May you create video, camera background blurring??

Blur camera background or any video inside OBS

Thank you

**Comment by FiniteSingularity** [comment]
Hi @elkhalafy,

Deep apologies for taking so long to get to this.  Unfortunately, doing background blurring (e.g.- nvidia background blurring, or zoom) is outside of the scope of this plugin, as it would require AI/Machine Learning like algorithms to separate the subject from the background.  I would recommend looking into one of the other available background removal plugins for OBS.
