### ISSUE TITLE
[BUG] - Blur duplicating a source

### ISSUE THREAD

**Issue by prgmitchell** [FiniteSingularity/obs-composite-blur#13]
**Describe the bug**
The preview for a source in it's properties looks normal but when actually looking at the OBS preview and output, there are duplicates of the source. The repro steps mention a browser source but I confirmed this to be the case on media source as well.

**To Reproduce**
1. Open OBS
2. Add a new browser source (you can leave all the default settings)
3. Add a composite blur filter to the browser source

**Expected behavior**
Blur should be applied, nothing additional.

**Screenshots**
![image](https://github.com/FiniteSingularity/obs-composite-blur/assets/86465454/170e1f78-a012-44f1-a506-a505a0d3bfd2)

**Environment**
 - OS/Version: Windows 11
 - OBS Version: 30.0.0 beta 2, also confirmed on 29.1.3 as well.
 - OBS Composite Blur Plugin Version: 0.0.3
 - Blur Algorithm/Type: Any besides Dual Kawase

**Additional context**
https://obsproject.com/logs/mL5FXDLV1eE3p6J5

**Comment by FiniteSingularity** [comment]
Thanks for reporting this.  The problem seems to be when a source is smaller than the entire canvas.  It looks like I'm missing a `gs_ortho` call on the 2-pass blur filters (Gaussian and Box).

**Comment by FiniteSingularity** [comment]
The PR above fixed the issue.  Will test it this evening and merge.

**Comment by prgmitchell** [comment]
@FiniteSingularity confirmed fixed, thanks!

![image](https://github.com/FiniteSingularity/obs-composite-blur/assets/86465454/035b7fac-f9cf-4ad3-85dd-fd0f037be9fe)

**Comment by FiniteSingularity** [comment]
@all-contributors please add @prgmitchell for bug
