### ISSUE TITLE
Blur Filter - Edge

### ISSUE THREAD

**Issue by alfasmartplayer** [FiniteSingularity/obs-composite-blur#15]
Actually I would say this plugin works great, but I can't apply a mask like in StreamFX. I would like to set Left, Right, Top, Buttom edges.
I think this would be very much needed as sometimes I need to mask any area in the image

https://prnt.sc/uYcY1NmzziCU

**Comment by FiniteSingularity** [comment]
Thank you for the feature request @alfasmartplayer.  Its a great idea.  In fact it is so great, that I started working on a feature branch to do masks last night, and am hoping to have it merged in today or tomorrow.  The branch will provide the following:

- [x] Crop Mask- where you can set Left, Right, Top, Bottom, and the option to give the mask rounded corners.
- [x] Source Mask- Provide another OBS source/scene to apply as a mask, with the option of the channel to use as the mask (r, g, b, or a), the ability to multiply the channel by a value.
- [x] Rectangle Mask- Similar to Crop Mask, but you would define the center of the mask, and a width/height
- [x] Circle Mask- User defined center and radius to create a circular mask.
- [x] Image Mask- Similar to source mask, but you provide a static image.

All masks will have the option to invert the mask as well.

**Comment by alfasmartplayer** [comment]
Do you have a contact address where I can reach you? I want to talk about some of my projects.

**Comment by FiniteSingularity** [comment]
Only deleting the message from alfa to keep the issue clean, as we took the side conversation elsewhere.
