### ISSUE TITLE
[BUG] - Composite Background option not working when filtered source is cropped.

### ISSUE THREAD

**Issue by FiniteSingularity** [FiniteSingularity/obs-composite-blur#20]
**Describe the bug**
If a filtered source that uses background source for compositing option, is cropped, the background compositing is no longer performed.

**To Reproduce**
1. Make a chroma-keyed facecam.
2. Place a solid light colored source behind the chroma keyed facecam.
3. Apply a gaussian blur to the face cam.
4. Set the color source as background source for compositing.
5. Witness the dark aura around the facecam.

**Expected behavior**
The facecam blur should not have a dark aura.

**Screenshots**
Before cropping
![image](https://github.com/FiniteSingularity/obs-composite-blur/assets/72580859/1b22740f-1265-4cf2-be79-96a66b0a49af)

After cropping
![image](https://github.com/FiniteSingularity/obs-composite-blur/assets/72580859/a58dc93f-68ab-4028-8e94-88a0b7fdc0d1)

**Environment**
 - OS/Version: Windows 11
 - OBS Version: Some dev version
 - OBS Composite Blur Plugin Version: 0.0.7-alpha with Exeldros PR merged in
 - Blur Algorithm/Type: All

**GPU**
 - GPU make/model: Nvidia RTX 3800
 - GPU VRAM: 12Gb

**Comment by FiniteSingularity** [comment]
A Workaround is to turn off SRGB blending off for the blurred source (facecam in the example above).

![image](https://github.com/FiniteSingularity/obs-composite-blur/assets/72580859/e7f68923-f16a-42a2-a91e-de48bc92dab9)

This seems to be due to a different rendering pipeline being used for cropped sources.  See https://github.com/obsproject/obs-studio/blob/321829d9324f7b82ef362ccc85f6dd053865080c/libobs/obs-scene.c#L550 (Thanks @exeldro for finding this).

**Comment by exeldro** [comment]
might need look into source output flag `OBS_SOURCE_SRGB` and `video_get_color_space` from the `struct obs_source_info`
like: https://github.com/obsproject/obs-studio/blob/321829d9324f7b82ef362ccc85f6dd053865080c/plugins/obs-filters/nvidia-greenscreen-filter.c#L1068

**Comment by FiniteSingularity** [comment]
This appears to have been fixed by #95
