### ISSUE TITLE
[BUG] - source size wrong when using background source for compositing

### ISSUE THREAD

**Issue by exeldro** [FiniteSingularity/obs-composite-blur#23]
**Describe the bug**
filtered source changes size when background source for compositing is used

**To Reproduce**
1. Have a full scene background source for compositing
2. Add a text source on top
3. Add blur filter on the text source
4. Set background source for compositing

**Expected behavior**
Only correct compositing when the source is top left, but always correct source size.

**Screenshots**
Without Background Source for Compositing:
![image](https://github.com/FiniteSingularity/obs-composite-blur/assets/5457024/cc61d4ed-f677-4fe1-97c7-d62ebb2bc881)
With Background Source for Compositing:
![image](https://github.com/FiniteSingularity/obs-composite-blur/assets/5457024/77eb7eb0-0ce5-455f-825b-269ceb0685c7)

**Environment**
 - OS/Version: Windows 11
 - OBS Version: 30.0.0-beta2
 - OBS Composite Blur Plugin Version: https://github.com/FiniteSingularity/obs-composite-blur/commit/4c833c8184a1149b368e2efb332f44230acdbdb3
 - Blur Algorithm/Type: Gaussian, Area

**GPU**
 - GPU make/model nvidia RTX 2060
 - GPU VRAM 6Gb

**Additional context**

**Comment by FiniteSingularity** [comment]
When creating the texture used for `background` in `composite.effect`, I was setting the orthographic projection to the background width and height, but wasn't setting it back to the source projection before calling `composite.effect`.  Once this was added, it works correctly.  Please give #24 a quick test and make sure it is fixing things for you as well.

**Comment by FiniteSingularity** [comment]
The PR should have fixed this.  Reopen if it is still an issue.
