### ISSUE TITLE
[BUG] - Masking causes incorrect scaling of sources that aren't the same size as the canvas

### ISSUE THREAD

**Issue by WonderWez** [FiniteSingularity/obs-composite-blur#44]
**My Issue:**
Encountering a scaling display issue when trying to add a composite blur to a section of my screen - my starting use case is to simply obscure the chat window in the lower left side of my game screen. My source is coming in as a Display Capture of my 1440p monitor into my 1080p profile, and I scale this larger source down to fit. Adding the basic Composite Blur (any algorithm) appears to work fine. However, when I try to apply any of the of the Effect Masks (barring "Source") using any of the blur algorithms, it removes my source scaling and cuts off the lower right area outside of the profile's base resolution. For many reasons, I am not willing to convert my project to the base resolution of my 1440p display.

I tested originally using my 1440p display monitor source, which initially showed the unexpected behavior. To test I tried on a 1080p display monitor source and it behaved as I would expect. I then tried on another type of source which I knew to be larger than 1080p in width (a PNG image file with dimensions of 2160x1350), and the same unexpected scaling behavior occurred.

I also attempted to apply the filter to the SCENE which singularly contained the source I wished to have the blur applied to, and the same unexpected behavior occurred.

**Steps to reproduce the behavior:**
1. In OBS, select a source that is natively larger than the OBS base resolution and is scaled down to fit (or a scene that contains a source meeting the same criteria) to apply the Composite Blur filter to.
2. Right-click the selected source and choose "Filters".
3. Click the "+" at the bottom left of the new Filters window and select the "Composite Blur" filter.
4. Name the filter and/or click "OK".
5. Select Blur Algorithm: (any)
6. Select Effect Mask: (Any except "None" or "Source")
7. The source resets it's scaling transform and the bottom right corner content of that source is cut off outside of the base resolution pixels (in my case 1920x1080).

**Expected Behavior:**
My hope is that the filter and effect mask would be applied to the entire source image instead of affecting only the unscaled base profile resolution, as I have plenty of larger-than-1080p sources that are brought in scaled.

**Screenshots**
Image 1: Displays the aspect of the source
![BlurIssue1](https://github.com/FiniteSingularity/obs-composite-blur/assets/144557600/fa50debd-5be1-454e-b157-723cd97aa822)

Image 2: Displays the expected behavior of the default Composite Blur added to the source, covering the entire image.
![BlurIssue2](https://github.com/FiniteSingularity/obs-composite-blur/assets/144557600/81dc5de9-002f-4749-a837-1265b9e58ebf)

Image 3: After Crop effect mask applied, showing the scaling removal of the source.
![BlurIssue3](https://github.com/FiniteSingularity/obs-composite-blur/assets/144557600/2a8e917f-f576-4d54-a2a3-18ede85d7454)

Image 4: Attempting to scale down the source again in the scene and revealing the content outside of the 1920x1080p is no longer visible. Tried hitting alt while pulling at those sides and nothing was able to be extended to its normal aspect.
![BlurIssue4](https://github.com/FiniteSingularity/obs-composite-blur/assets/144557600/5073be10-8ef6-41f6-a339-1d2dfb162ddb)

**Environment**
 - OS/Version: Windows 11 Home, Version 22H2, OS Build 22621.2134
 - OBS Version: 29.1.3
 - Composite Blur Plugin Version: 1.0.0
 - Blur Algorithm/Type: All algorithms, All effect masks (except None and Source).

**GPU**
 - GPU make/model: NVIDIA RTX 3080
 - GPU VRAM: 10GB
 - GPU Driver: GeForce Game Ready Driver 537.13 (8/22/2023)

**Comment by FiniteSingularity** [comment]
@WonderWez- Thank you for opening the issue.  I've already found the issue and fixed it in PR #43 .  Can you please download the plugin that was built from that PR (go to the actions page: https://github.com/FiniteSingularity/obs-composite-blur/actions/runs/6132778354 , then scroll down to the bottom, where you'll see a section for "Artifacts".  Grab the installer for whatever OS you are using).  Then quit your copy of OBS, run the installer, and see if it resolves your issue?

**Comment by WonderWez** [comment]
@FiniteSingularity - Thank you for your prompt action on this! Performing the same steps now gives me the expected behavior, and I was able to apply any of the effect masks with successful results using all of the algorithms.

**Comment by FiniteSingularity** [comment]
Great to hear!  I'll merge it in, and get a new release out later this afternoon.

**Comment by FiniteSingularity** [comment]
@all-contributors please add @WonderWez for bug

**Comment by FiniteSingularity** [comment]
Fixed with PR #43
