### ISSUE TITLE
[BUG] - Masking bugs when using scaled source and radius 0

### ISSUE THREAD

**Issue by ASchneiderBR** [FiniteSingularity/obs-composite-blur#54]
## Describe the bug 

Two new issues observed after latest update:

1. When using a 4K image source scaled down to 1080p via Scaling/Aspect Ratio filter as a blur mask, the mask only covers 1/4 of the frame instead of full frame. Seems it is using the original 4K mask size rather than scaled 1080p output.

2. Using a Dual Kawase blur with radius 0 causes the video to freeze, showing only the mask image over a frozen frame. Other algorithms work fine at radius 0.

## To Reproduce

1. Add 4K image source
2. Add Scaling/Aspect Ratio filter to scale to 1080p
3. Add 1080p video source to blur 
4. Add Composite Blur to video, mask using scaled image source
5. Mask only covers 1/4 of frame

6. On new Composite Blur filter, set Dual Kawase algorithm and radius to 0
7. Video freezes, only mask image displays

## Expected behavior

1. The scaled 1080p mask should cover the entire 1080p frame of the blurred video source.

2. Dual Kawase blur with radius 0 should show unblurred source video under mask.

## Screenshots

https://streamable.com/d4we20

## Environment

- OBS Version: 30.0.3 beta
- Composite Blur Version: 1.0.2
- GPU: Nvidia RTX 2080 Ti
- Windows 11

## Additional context

Previous alpha masking issue was fixed in latest update, but found these new bugs when testing further.

**Comment by FiniteSingularity** [comment]
I think I've got a fix for the scaling issue, just testing it to make sure it doesn't have any unintended consequences.

Regarding the Dual Kawase Blur, this is related to issue #17 .  For both pixelate and Kawase, values of 0 are basically undefined mathematically, as both are a mapping.  e.g.- 1:1 mapping of pixels is just the original image, 1:2 is double the number of pixels, or in the case of Kawase, blurring 2 pixels together, etc.

I assume you are trying to set the Dual K blur via something like the Move plugin, as the sliders shouldn't allow values smaller than 1.  So the first thing that needs to be done (and the easy part) is to check the user input and if the user enters zero, pass a 1 instead (e.g.- pass `max(1, user_input)`).  The harder question to answer- do we allow the sliders to go to zero, and do the same?  It may lead to fewer questions, but some people may be confused when zero blur is the same as the blur at 1 (i.e.- no blur at all).

(You may wonder- isn't Gaussian and Box blur also a mapping.  The answer would be no, they are a convolution, where the input value for radius, is the distance from the center.  So a value of 0.0 is the center of the original pixel, e.g. no blurring, 1.0 is the center of the adjacent pixels, 2.0 is 2 pixels over, etc.)

**Comment by FiniteSingularity** [comment]
Oops.. nevermind.. now I am seeing the Kawse Blur issue, and it is something completely different.  Investigating...

**Comment by ASchneiderBR** [comment]
Hello, thanks for the information. It does make a lot more sense to me to have the 0 as "zero/no blur" parameter, just like box and gaussian. Maybe a "fake zero" would be the perfect solution :) That would help a lot when animating with move filter and. Thanks for your time.

**Comment by FiniteSingularity** [comment]
Ok, so I've got a PR up for this fix.  @ASchneiderBR, when the build action is finished running (it takes about 15 minutes from when the PR is created), would you be willing to try out the new code and see if it fixes your issue?  If so, just navigate to the action page for the PR ( https://github.com/FiniteSingularity/obs-composite-blur/actions/runs/6152383057 ), and once all is done building, you'll find an "artifacts" section at the bottom of the page.  Download the installer/zip for your OS, and install like you normally would, and give it a try.

I made the decision to allow zero on the slider for Dual Kawase, as it is only one step.  For the Pixelate, I am still going to keep the minimum at 1.0 (which is zero pixelization), as otherwise we have an awkward 10-step zone between 0 and 1 where no pixelization occurs.

**Comment by ASchneiderBR** [comment]
Got it! Will test it ASAP and let you know. Thanks!

**Comment by ASchneiderBR** [comment]
Hello. Just tested it and everything is working perfectly :) Amazing work!

https://github.com/FiniteSingularity/obs-composite-blur/assets/25224882/c0554510-c87a-4a16-8aca-29f1b2d22c82

I loved the "zero" parameter for no blur at all. The only suggestion is to have it as well for the pixelate, 0 for no blur.

Thanks!

**Comment by FiniteSingularity** [comment]
So Pixelate has a zero-blur passthrough as well.  It just happens at the value of 1.  I don't feel like there is a "correct" answer on this one.. 🤣

**Comment by ASchneiderBR** [comment]
Thanks for your help. I wonder if there's a way to display 1 as 0, 1.5 as 0.5, etc. in the formula. That might make it easier for people like me who don't understand the pixelation logic behind it. 😅

Just a suggestion... Anyway, you solved all my issues, so I appreciate it. Have a nice day!

**Comment by FiniteSingularity** [comment]
You're welcome.  I'll definitely give it some thought, as I want the plugin to be as easy to understand/use as possible, and I do realize that this bit is a little confusing.  Its easy enough to add 1 to the input value (so zero becomes 1, etc..).

For now I'm going to test out this PR a bit, and merge it in.  It probably wont make it into a release for a day or two (as I just did a release a couple of hours ago).  But the PR version you're currently running should be fully functional, so you can use that until there is a new release.  Cheers!

**Comment by ASchneiderBR** [comment]
Hello again! I have a suggestion to potentially simplify the scale parameter: instead of an absolute value, what if it used a percentage from 0 to 100 with decimals? This percentage-based scale could allow for more intuitive fine-tuning. Just an idea :)

I was watching your last Twitch stream and was amazed by the upcoming stroke plugin - it's something I've wanted for ages! The plugin looks incredibly versatile and user-friendly. Thank you for all your hard work developing these tools for the OBS community. Keep up the great work, and have an excellent day!
