### ISSUE TITLE
How to install composite blur on ubuntu 22.04?

### ISSUE THREAD

**Issue by hdnminh** [FiniteSingularity/obs-composite-blur#67]
![image](https://github.com/FiniteSingularity/obs-composite-blur/assets/76483242/f01a580b-fa89-421c-a32e-8d99d7b37efe)
I have no idea to install it. Please help me. Thanks in advance

**Comment by FiniteSingularity** [comment]
Hi @hdnminh.  Unfortunately, I've not got a Linux/Ubuntu machine to try the installation on, and have never installed.  There are a couple of Linux users who have gotten it working properly and tested it for me.  I've asked one of them to provide some instructions here (and in the Readme).  They'll be posting some instructions for you a little later today.

**Comment by SketchNI** [comment]
Hi, @hdnminh! It looks like you're using Ubuntu?

- Extract the entire `obs-composite-blur` folder
- Navigate to your `~/.config/obs-studio/plugins` folder
- Copy/Move `obs-composite-blur` to the `plugins` folder

The folder path should now look like `~/.config/obs-studio/plugins/obs-composite-blur`

**Comment by FiniteSingularity** [comment]
Thank you @SketchNI!  I'll leave this open for a bit until I get the docs PR you opened merged in.

**Comment by FiniteSingularity** [comment]
@hdnminh - I've merged in the docs provided by @SketchNI into the Readme.me file. If you are still having issues installing after reading, feel free to reopen this issue.

**Comment by hdnminh** [comment]
Hi @FiniteSingularity, @SketchNI,
My host (ubuntu 22.04) does not have /plugins folder. So I try to put obs-composite-folder into subfolder below, but it's still not working.

![image](https://github.com/FiniteSingularity/obs-composite-blur/assets/76483242/09d2fe5e-2e4d-4745-85c1-e6f13824f5a7)
![image](https://github.com/FiniteSingularity/obs-composite-blur/assets/76483242/f12bf33a-f2c3-4775-9d1d-abcc2c8322d0)

**Comment by FiniteSingularity** [comment]
`plugin_config` will hold the configuration files for the plugins that ops generates, but not the actual plugins.  Try making a new `plugins` directory inside of `.config/obs-studio` and place the `ops-composite-blur` directory in that new `plugins` directory.

So it should look like:
`Home/.config/obs-studio/plugins/obs-composite-blur`

**Comment by hdnminh** [comment]
Hi @FiniteSingularity 

It's still not working, even if I restart my laptop :((
![image](https://github.com/FiniteSingularity/obs-composite-blur/assets/76483242/f060aafb-1654-4683-8f38-19274b5a6837)

**Comment by FiniteSingularity** [comment]
@hdnminh it looks like OBS isn't loading plugins from the typical place.  Can you please run OBS and post the log file?  Maybe we can determine the location it is loading plugins from.

**Comment by hdnminh** [comment]
Hi @FiniteSingularity, here is the log file.
[2023-09-18 08-41-08.txt](https://github.com/FiniteSingularity/obs-composite-blur/files/12645123/2023-09-18.08-41-08.txt)

**Comment by FiniteSingularity** [comment]
Unfortunately, the log file isn't indicating where plugins are loading from.  And the guidance in the OBS documentation, and where other people have successfully had the plugin run, is in `~/.config/obs-studio/plugins` as is indicated here: https://obsproject.com/kb/plugins-guide (see the Install or Remove plugins section at the bottom). I'm not sure I can help any more, as I personally don't have OBS running in a linux environment.  I'll re-open this issue, and see if anyone else with more Linux experience has any ideas.

**Comment by FiniteSingularity** [comment]
@hdnminh quick question- were the plugin files installed when you ran OBS and grabbed that log file?

**Comment by hdnminh** [comment]
It's suddenly working now. Thanks @FiniteSingularity so much.

**Comment by FiniteSingularity** [comment]
Glad to hear it is working for you.  Enjoy the plugin!
