### ISSUE TITLE
[BUG] - Pixelate causes strange behavior when set to 1px

### ISSUE THREAD

**Issue by JDDoesDev** [FiniteSingularity/obs-composite-blur#76]
**Describe the bug**
Recently upgraded to 1.0.3. I use a move value transition to increase pixel size based on channel redeem, with initial setting of 1.00.  After upgrading the filter creates a trail of the video.  Only seems to be a problem when using chroma key. See image:

**To Reproduce**
1. Go to create new composite blur filter
2. Select Pixel (Any variation works)
3. Set pixel size value to 1.00
4. Notice trail
5. Increase pixel size value to >1.00 (1.01 worked)
6. Notice trail disappears

**Expected behavior**
No trail.

**Screenshots**
![image](https://github.com/FiniteSingularity/obs-composite-blur/assets/9932557/0b6222f5-468a-4979-a85a-96620794d243)

**Environment**
 - OS/Version: [e.g. Windows 11]
 - OBS Version: [e.g. 29.1.2]
 - Composite Blur Plugin Version: [e.g. 1.0.3]
 - Blur Algorithm/Type: [e.g. Blur, Area]

**GPU**
 - GPU make/model [e.g.- nvidia RTX 3070]
 - GPU VRAM [e.g.- 8Gb]

**Additional context**

**Comment by FiniteSingularity** [comment]
Thank you for the issue.  I will take a look this afternoon.

**Comment by FiniteSingularity** [comment]
Confirmed the bug, and it happens on all blur types.  Working on a fix now.

**Comment by FiniteSingularity** [comment]
Please let me know if the PR fixes your issue.  Even if not, it'll be merged in shortly as it could fix other potential issues as well.

**Comment by JDDoesDev** [comment]
@FiniteSingularity can confirm issue is fixed with new PR.
![image](https://github.com/FiniteSingularity/obs-composite-blur/assets/9932557/cdb35f13-2c75-4bb0-bddc-f84e7c866615)

**Comment by FiniteSingularity** [comment]
Glad to hear it!  Just merged in the PR.  Thanks for opening the issue @JDDoesDev.
