### ISSUE TITLE
[BUG] - Runaway memory leak with Composite Blur filter applied to capture source with no connected application

### ISSUE THREAD

**Issue by Poodmund** [FiniteSingularity/obs-composite-blur#82]
**Describe the bug**
I am seeming to get a runaway memory leak in certain conditions when using the Composite Blur plugin when I switch between scenes that have a composite blur filter applied to Window or Game Capture sources, when the sources are active, but the sources have no application to connect to (therefore the filter is being applied to nothing).

The example in this case occurs when switching between a scenes containing a desktop capture source, a scene containing a Chrome window capture source, a scene containing a game capture source that is visible but the game is not running and a scene containing an application capture source that is visible but the application is not running. Both of this capture sources have a composite blur filter applied to them using:

**To Reproduce**
1. Create two scenes, (a) one being blank and (b) one with a Window/Game capture source of an open application and apply a Composite Blur filter against the captured sourced BUT importantly, close the application so that the source is not connected to the application.
2. Navigate to the blank scene (a).
3. Navigate back to the scene with the Composite Blur filter (b) and notice that the memory allocated to OBS runs away to max capacity in a few seconds.

**Expected behavior**
I would expect that the Composite Blur filter being applied to the capture source is not being applied to the source when there is not texture to render.

**Environment**
 - OS/Version: Windows 10
 - System RAM: 32GB DDR4
 - OBS Version: OBS Studio 30.0 Beta 3
 - Composite Blur Plugin Version: Release 1.0.4
 - Blur Algorithm/Type: Occurs on all algorithm types.

**GPU**
 - GPU make/model: Nvidia RTX 3070
 - GPU VRAM: 8 GB GDDR6

**Additional context**
Early investigation by FiniteSingularity: "I have an early exit for the filters if they don't see a texture to blur. I was properly cleaning things up, but didn't early-exit the masking code.  So, its the attempted mask on the non-running source that is causing the issue, not the non-running source itself."

**Comment by Poodmund** [comment]
Tested the build from https://github.com/FiniteSingularity/obs-composite-blur/actions/runs/6290618877 and it appears to resolve my issue. Thank you.

**Comment by FiniteSingularity** [comment]
@all-contributers please add @Poodmund for bug

**Comment by FiniteSingularity** [comment]
@all-contributors please add @Poodmund for bug

**Comment by FiniteSingularity** [comment]
@Poodmund, thank you for the bug report, and for confirming the fix.  Just merged that PR into the main branch, and will make a new release.
