### ISSUE TITLE
[FEATURE] - Toggle Filters via Hotkey

### ISSUE THREAD

**Issue by LogicalSoIutions** [FiniteSingularity/obs-composite-blur#90]
**Is your feature request related to a problem? Please describe.**
I just am looking for an easy way to toggle my BLUR via a Hotkey. 

**Describe alternatives you've considered**
Tried the LUA script that exists for using Hotkeys for Filters but it resets every time I restart OBS and I want persistence.

**Comment by FiniteSingularity** [comment]
Hi @LogicalSoIutions,

Thank you for the feature request- great idea! I will look into adding hotkeys as a part of the next feature release.
